# Generated by Django 3.0.3 on 2020-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200217_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='born_date',
        ),
        migrations.AddField(
            model_name='human',
            name='birth_date',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='human',
            name='birth_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='human',
            name='birth_year',
            field=models.IntegerField(default=1370),
        ),
        migrations.AlterField(
            model_name='account',
            name='educational_status',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('GRADUATED', 'Graduated'), ('ETC', 'Etc')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='grade',
            field=models.CharField(choices=[('PHD', 'Phd'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], max_length=20),
        ),
    ]
