# Generated by Django 3.0.3 on 2020-02-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200217_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='caravan',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('MEN', 'Men'), ('WOMEN', 'Women')], default=None, max_length=20),
        ),
    ]
