# Generated by Django 3.0.3 on 2020-02-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_account_caravan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='spouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spouse', to='accounting.Human'),
        ),
        migrations.AddField(
            model_name='human',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.Human'),
        ),
    ]
