# Generated by Django 3.0.3 on 2020-02-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20200218_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Human'),
        ),
    ]
