# Generated by Django 2.0 on 2020-02-22 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20200218_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='spouse',
        ),
        migrations.AddField(
            model_name='account',
            name='return_destination',
            field=models.CharField(blank=True, default='TEHRAN', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='spouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='spouse_related', to='accounting.Human'),
        ),
        migrations.AlterField(
            model_name='account',
            name='caravan',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='educational_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
